# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: main
    directory: "src/nvcgo/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
    - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    target-branch: gh-pages
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
